# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plist < Formula
  desc "CLI tool to convert Apple's plist files into Yaml and Json."
  homepage "https://github.com/aurc/homebrew-tap"
  version "1.1.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aurc/plist/releases/download/v1.1.10/plist_1.1.10_darwin_arm64.tar.gz"
      sha256 "1d74f007d7b0dfc9ca6a8bfbd7d639c68d572cfe70d368f1651d1ffe19df97e0"

      def install
        bin.install "plist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aurc/plist/releases/download/v1.1.10/plist_1.1.10_darwin_amd64.tar.gz"
      sha256 "1f75cad00b05eefda96fb0bca71dacaa1eadfc02fbf69308ef4be3cedcb59400"

      def install
        bin.install "plist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aurc/plist/releases/download/v1.1.10/plist_1.1.10_linux_arm64.tar.gz"
      sha256 "fb066d8943fd74a948c3f78f10df416775cd5c0bbc692336945b800c0e042069"

      def install
        bin.install "plist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aurc/plist/releases/download/v1.1.10/plist_1.1.10_linux_amd64.tar.gz"
      sha256 "5863ad54d8816481695a0fde2caa8c4e4e805e79fed57993d81c3b675e015cfb"

      def install
        bin.install "plist"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
